// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhUt8M1fOqkQUEQmspUhFLRDi7RhK_lTs',
    appId: '1:474193537658:web:99cd7761bfb3f241e669c3',
    messagingSenderId: '474193537658',
    projectId: 'emolog-37614',
    authDomain: 'emolog-37614.firebaseapp.com',
    storageBucket: 'emolog-37614.firebasestorage.app',
    measurementId: 'G-QNKZDX805V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG5LWzvckRAIKd9ACd8INxexvTNvDXm4c',
    appId: '1:474193537658:android:2427b4cee79e5a7ce669c3',
    messagingSenderId: '474193537658',
    projectId: 'emolog-37614',
    storageBucket: 'emolog-37614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1dwvJimyBxUAFwX-WdGeL2-xUscJzBzk',
    appId: '1:474193537658:ios:1d45ff5d49118ed1e669c3',
    messagingSenderId: '474193537658',
    projectId: 'emolog-37614',
    storageBucket: 'emolog-37614.firebasestorage.app',
    iosBundleId: 'com.example.emolog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1dwvJimyBxUAFwX-WdGeL2-xUscJzBzk',
    appId: '1:474193537658:ios:1d45ff5d49118ed1e669c3',
    messagingSenderId: '474193537658',
    projectId: 'emolog-37614',
    storageBucket: 'emolog-37614.firebasestorage.app',
    iosBundleId: 'com.example.emolog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhUt8M1fOqkQUEQmspUhFLRDi7RhK_lTs',
    appId: '1:474193537658:web:0eb0bc77bb7c0b51e669c3',
    messagingSenderId: '474193537658',
    projectId: 'emolog-37614',
    authDomain: 'emolog-37614.firebaseapp.com',
    storageBucket: 'emolog-37614.firebasestorage.app',
    measurementId: 'G-CQGV2EX11K',
  );
}
